include:
  # - local: "/templates/.gitlab-ci-aquasec-trivy-scan.yml"
  # - local: "/templates/vars/.gitlab-ci-pipeline-coe-vars.yml"
  # - local: '/templates/.gitlab-ci-aws.yml'
  # - local: '/templates/.gitlab-ci-docker-build.yml'
  # - local: '/templates/.gitlab-ci-checkov-scan.yml'
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Terraform.latest.gitlab-ci.yml

stages:
  - .pre
  - build
  - scan
  - validate
  - fmt
  - deploy
  - terraform plan
  - checkov scan
  - terraform apply
  - test
  - cleanup


# variables:
#   WORKING_DIR: .
#   DOCKER_REGISTRY: $CI_REGISTRY_IMAGE
#   IMAGE_NAME: node-image
#   IMAGE_VERSION: $CI_COMMIT_SHORT_SHA
#   DOCKER_USER: $CI_REGISTRY_USER
#   DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
#   DOCKER_TARGET_IMAGE: $IMAGE_NAME:$IMAGE_VERSION
#   SBOM_FILE: trivy.cdx.json

# before_script:
#   - export VARIABLE_NAME=ROLE_ARN
#   - |
#     STS=($(aws sts assume-role-with-web-identity \
#     --role-arn ${ROLE_ARN} \
#     --role-session-name "Ship-Devops-${CI_PIPELINE_ID}-${CI_JOB_ID}-Session" \
#     --web-identity-token ${GITLAB_OIDC_TOKEN} \
#     --duration-seconds 3600 \
#     --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
#     --output text))
#     export AWS_ACCESS_KEY_ID="${STS[0]}"
#     export AWS_SECRET_ACCESS_KEY="${STS[1]}"
#     export AWS_SESSION_TOKEN="${STS[2]}"
# after_script:
#   - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  stage: build
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME
