variables:
  AWS_DEFAULT_REGION: "ap-southeast-1"

.check-variable-sh: &check-variable-sh
  script:
    - if [ -z "$(eval echo \$$VARIABLE_NAME)" ]; then echo "$VARIABLE_NAME must be set. $CUSTOM_MSG" && exit 1; fi
    - export TEMPLATE_NAME=".check-variable-sh"

.invoke-awscli-commands-with-assumerole:
  image:
    name: $NEXUSREPO_DOCKER_PROXY_HOSTNAME/amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://$CI_SERVER_HOST
  tags:
    - non_privileged
    - no_root
    - cstack
  before_script:
    - export VARIABLE_NAME=ROLE_ARN
    - .check-variable-sh, script
    - |
      STS=($(aws sts assume-role-with-web-identity \
      --role-arn ${ROLE_ARN} \
      --role-session-name "Devops-${CI_PIPELINE_ID}-${CI_JOB_ID}-Session" \
      --web-identity-token ${GITLAB_OIDC_TOKEN} \
      --duration-seconds 3600 \
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
      --output text))
      export AWS_ACCESS_KEY_ID="${STS[0]}"
      export AWS_SECRET_ACCESS_KEY="${STS[1]}"
      export AWS_SESSION_TOKEN="${STS[2]}"
  after_script:
    - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    - export TEMPLATE_NAME=".invoke-awscli-commands-with-assumerole"
