name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN:  ${{ secrets.GITLAB_TOKEN }}
          SGTS_GITLAB_TOKEN:  ${{ secrets.SGTS_GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: 60742744
          SGTS_GITLAB_PROJECT_ID: 45456
         
        run: |
          curl --request POST \
            --form "token=$GITLAB_TOKEN" \
            --form "ref=main" \
            --form "variables[BUILD_TRIGGER]=true" \
            --form "variables[PIPELINE_TYPE]=infra" \
            --form "variables[TASK_DIR]=eks-cluster" \
            "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/trigger/pipeline"
